name: CI for main.py

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
      id: pytest  # ID to reference the result later

  send_email:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Send success email if tests succeed
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com  # Change to your SMTP server if necessary
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Succès des tests"
        body: "Tous les tests ont réussi."
        to: "m.fanget@tkminnovation.io"
        from: "github.action.groupe2@gmail.com"
